### PR TITLE
Remove some code duplication

### PR DESCRIPTION
**Pull request by cpgr**
I've condensed `BrineFluidPropertiesBeta` so that it only contains the new halite solubility code you added. All of the other functionality should flow from `BrineFluidProperties`.

I also added a much simpler test to see if everything will equilibrate in a single block.

### CODE REVIEW

**Review by iyevugah — APPROVED** [review]
Great! Thanks for the feedback @cpgr

**Comment by cpgr** [comment]
I don't think I deleted any of your new stuff, but you might want to double check!

I've been thinking about this and I think the flow should be like:

- Check whether Xnacl is greater than Xeq
- If it isn't, there is no solid phase so proceed as per BrineCO2
- If it is, then Xnacl is set to Xeq (so salt at equilibrium again in liquid phase)
- The solid phase saturation is then computed - it should be something like (Xnacl - Xeq) * rho_brine / rho_halite (might be missing something)
- Snacl set to 1 (only salt in solid phase)
- Then all properties are computed

**Comment by iyevugah** [comment]
Sure, @cpgr. I'll work on it and get back to you shortly..

**Comment by iyevugah** [comment]
Hello @cpgr, I’m not sure `Xnacl` needs a switch to `XEQ` since I’m using the persistent variable (`Z`). The `phaseState` method seems to guide the phase switch using `Z`. To properly represent all the 6 `phaseState` combinations (i.e.,` L`, `G`, `L+G`,` L+S`, `G+S` and `L+G+S`), perhaps the flow should build upon your proposed flow as follows:

•	Check whether `Xnacl` is greater than `XEQ` and proceed as `BrineCO2` if it isn’t. `BrineCO2` has `L`, `G` and `L+G`.
•	Otherwise, `Xnacl` is greater than `XEQ`, and the solid phase appears. The flow continues as follows:

1.	Compare the persistent variable (`Z`) with its minimum value (`Zmin`); if `Z < Zmin`, then there is `L+S` (Just like `BrineCO2`, but with the salt component).
2.	If `Z > (1-Z)`, then there is `G+S`. Note: `1-Z` is the liquid version of the persistent gas variable, ` Z`. 
3.	Else, all three phases exist (i.e., `L+G+S`). 
I did this, and my simulation ran and converged up to a point and then failed. Please, let me know what you think. Thanks.

**Pull request merged**
